### ISSUE TITLE
Evaluating (Tropical) Circulation and the implications for oxygen minimum zones and other things...

### ISSUE THREAD

**Issue by jbusecke** [matt-long/cmip6hack-ocean-o2#7]
Hi everyone, 

I would like to focus on the equatorial circulation, and how it changes between models and under forcing. 
I think this could be helpful for the context of several bgc projects and also the [tropical SST gradient project](https://discourse.pangeo.io/t/response-of-tropical-pacific-ssts-to-climate-forcing-in-cmip6/227/2).

Ill start of with a basic evaluation. Please join me if you are interested, or tell me what aspect of this could be important for other projects.

**Comment by matt-long** [comment]
@jbusecke, could you briefly describe you basic evaluation? It would be nice to integrate with #5. 

Can we explain O2 biases in the context of physical biases?

**Comment by jbusecke** [comment]
My particular interest lies in the influence of the EUC on the upper OMZ, but that is a bit of my pet peve. 
Here at Lamont we have started to split up, and I will start with trying to produce global overturning streamfunctions. I think that is a good first step to evaluate generally the role of ventilation? What do you think? 

In the coming days I would like to evaluate if the relationship between the forced changes in EUC to the Volume of the OMZ found by [Shigemitsu et al. 2018](https://agupubs.onlinelibrary.wiley.com/doi/pdf/10.1002/2016GB005447), which we argue in [Busecke et al. 2019](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2019GL082692) is an artifact of the EUC being poorly represented in most CMIP5 models.
